# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MagazineReader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MagazineReader
  
  pod 'Moya'
  pod 'SnapKit'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'Reusable'
  pod 'Then'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'EmptyDataSet-Swift'
  pod 'JXPagingView/Paging'
  pod 'JXCategoryView'
  pod 'YYCache'
  pod 'FMDB'
  
  pod 'WoodPeckeriOS', :configurations => ['Debug']

end
