# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MagazineReader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MagazineReader
  
  pod 'Moya'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'LLCycleScrollView'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'EmptyDataSet-Swift'

end
